kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ticket
  namespace: sbs-dev
spec:
  rules:
  - host: ticket.intern-we.drift.azure.nrk.cloud
    http:
      paths:
      - backend:
          serviceName: ticket
          servicePort: 80
        path: /
---

kind: Service
apiVersion: v1
metadata:
  name: ticket
  namespace: sbs-dev
  labels:
    app: ticket
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: ticket

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: ticket
  namespace: sbs-dev
  labels:
    app: ticket
  annotations:
    nrk/email-contact: anders.ween@nrk.no
    nrk/documentation: 'https://confluence.nrk.no/display/STIL'
    nrk/slack-notification: '#sbs-notifications'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket
  template:
    metadata:
      labels:
        app: ticket
    spec:
      containers:
        - name: ticket
          image: 'plattform.azurecr.io/sbs/ticket:BUILDNUMBER'
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi